on:
  workflow_call: # Called via release.yml

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            suffix: windows
            artifact: "AeroflyStartgeraet-Windows.exe"
          - os: macos-latest
            suffix: macos
            artifact: "AeroflyStartgeraet-MacOS.dmg"
          - os: ubuntu-latest
            suffix: linux
            artifact: "AeroflyStartgeraet-Linux.AppImage"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Linux build deps
        if: runner.os == 'Linux'
        run: sudo apt-get install -y fakeroot

      - name: Build GUI application
        run: |
          mkdir -p ./artifacts/gui
          npx electron-builder --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gui-artifact-${{ matrix.suffix }}
          path: ./artifacts/gui/${{ matrix.artifact }}
